### ISSUE TITLE
OGMS home URL out of date

### ISSUE THREAD

**Issue by BAevermann** [OntoZoo/ontobee#117]
at: 
http://www.ontobee.org/ontology/OGMS

in description:
Home: http://code.google.com/p/ogms/

should be: 
https://github.com/OGMS/ogms

Thanks,

Brian Aevermann

PS: can you also change the contact to baeverma@jcvi.org?

**Comment by e4ong1031** [comment]
Both the home page link and contact information are updated.

Thanks,
Edison

**Comment by mcourtot** [comment]
HI @e4ong1031 - do you get this info from the OBO md files or somewhere else? It'd be good to keep in sync and have only one place to update.

**Comment by e4ong1031** [comment]
Hi @mcourtot, Yes, the information should be from OBO registry. I checked the OBO website, and the content there actually is not updated. The homepage is still code.google.com and the contact is Albert Goldfain. Thanks for pointing it out.

@BAevermann Please also update the information on OBO as well. Otherwise, Ontobee will display the outdated information after the next update.

**Comment by mcourtot** [comment]
Thanks @e4ong1031! 
@BAevermann let me know if any issue doing the PR on the OBO side.

**Comment by BAevermann** [comment]
Thanks everyone. Ill look into updating the OBO info.

**Comment by cmungall** [comment]
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/467

**Comment by BAevermann** [comment]
@mcourtot I am unclear as to the best way to proceed. Should I fix the necessary descriptions via a PR or use the issue tracker at OGOFoundry?

**Comment by mcourtot** [comment]
@BAevermann - sorry didn't see this comment, but the PR was done and merged.
