### ISSUE TITLE
Ontologies are out of date

### ISSUE THREAD

**Issue by cmungall** [OntoZoo/ontobee#141]
http://www.ontobee.org/ontology/MONDO - 2018-06-08 - there have been [4 releases](https://github.com/monarch-initiative/mondo/releases) since then

http://www.ontobee.org/ontology/UBERON 2018-03-09 - this is an old version there have been a number of releases since then

I think many more are out of date

Would it be possible to have ontobee be more transparent about build frequencies. Why not inject this metadata into the triplestore - e.g. write a triple any time the store is updated

**Comment by yongqunh** [comment]
I checked this with Edison. For the MONDO update, the problem is that when the script tried to merge the importing ontologies, the following import ontology is not available: 
https://raw.githubusercontent.com/monarch-initiative/mondo-build/master/imports/ecto_import.owl.  
Therefore, Ontobee failed to update the new releases since 2018-06-08.

It’s a good suggestion to make Ontobee more transparent about build frequencies. We are working on this …
Thanks, Oliver

**Comment by cmungall** [comment]
Oops! The missing import is now fixed.

Any idea about Uberon?

**Comment by cmungall** [comment]
Missing import fixed - can we get a MONDO update?

**Comment by yongqunh** [comment]
A MONDO update is done now:
http://www.ontobee.org/ontology/MONDO
thanks.
