### ISSUE TITLE
Is DOID included in OntoBee?

### ISSUE THREAD

**Issue by linikujp** [OntoZoo/ontobee#192]
Hi, can you double check if DO files included? I could find the DOID terms by searching the OntoBee interface.

**Comment by yongqunh** [comment]
Updated: https://ontobee.org/ontology/DOID

**Comment by allenbaron** [comment]
Hi @yongqunh, it seems some DO terms can be found by a search in Ontobee but only if they are used in other ontologies. It looks like Ontobee is not loading the Human Disease ontology file itself.

Is there something we need to do as developers of the ontology to fix this?

<img width="646" alt="image" src="https://github.com/OntoZoo/ontobee/assets/21225409/f5760dd3-1ed5-46d7-b99b-50e08c15a26e">

@lschriml

**Comment by yongqunh** [comment]
Thanks for reporting. 
DOID should be back now to Ontobee:
https://ontobee.org/ontology/DOID

**Comment by lschriml** [comment]
Great !! Thank you Oliver !!Sent from my iPhoneOn Sep 1, 2023, at 10:34 AM, Yongqun Oliver He ***@***.***> wrote:﻿
Thanks for reporting.
DOID should be back now to Ontobee:
https://ontobee.org/ontology/DOID

**Comment by allenbaron** [comment]
Hi @yongqunh,
This issue appears to recur every time a new release of the Disease Ontology is created. I'm guessing that the issue is that doid.owl has import statements and is not the "full" product (all imports merged in), like other OBO Foundry ontologies.

If that's the case, is it possible to set the Ontobee server to use the doid-merged.owl file instead of doid.owl? It's PURL is http://purl.obolibrary.org/obo/doid/doid-merged.owl.

Is there something I can do to help ensure that the data is loaded correctly with each release?
<br>

> [!NOTE]
> OLS now loads `-international.owl` files for a number of OBO Foundry ontologies by default. `doid-international.owl`, like others, is the "full" ontology with all language translations included (for DO English & Spanish currently). If this file is desired, it's PURL is http://purl.obolibrary.org/obo/doid/translations/doid-international.owl.
