### ISSUE TITLE
usage in external ontologies not showing for ObjectProeprties

### ISSUE THREAD

**Issue by cmungall** [OntoZoo/ontobee#27]
E.g.
http://purl.obolibrary.org/obo/RO_0002202

Works for usage within an ontology:
http://www.ontobee.org/browser/rdf.php?o=UBERON&iri=http://purl.obolibrary.org/obo/RO_0002202

**Comment by e4ong1031** [comment]
http://purl.obolibrary.org/obo/RO_0002202 will link the term, RO_0002202, within RO ontology. (o=RO)

http://www.ontobee.org/browser/rdf.php?o=UBERON&iri=http://purl.obolibrary.org/obo/RO_0002202 will link to the term within UBERON ontology (o=UBERON).

So the usage will not show up when using the purl URL since it is under different ontology.
But you can redirect using the link inside the "Ontologies that use the XXXX" section.
