### ISSUE TITLE
search for synonyms

### ISSUE THREAD

**Issue by nicolevasilevsky** [OntoZoo/ontobee#35]
Could we add the ability to search for synonyms when searching ontologies in Ontobee?

**Comment by cindyJax** [comment]
I would also find such a feature useful.

**Comment by ontoden** [comment]
I think Ontobee can already search for synonyms.
You can provide some examples if it is not the case.
Thanks,
Oliver

**Comment by cindyJax** [comment]
A search for "vertebral body' does not return 'bony vertebral centrum'

A search for 'von Ebner's gland' does not return 'gustatory gland'

**Comment by ontoden** [comment]
But the term 'bony vertebral centrum' is not a synonym of 'vertebral body':
http://www.ontobee.org/browser/rdf.php?o=VIVO-ISF&iri=http://purl.obolibrary.org/obo/UBERON_0001075

'vertebral body' is indeed a synonym of 'body of vertebra'. The 'body of vertebra' is the label of the term. 'vertebral body' is its synonym. When you search 'vertebral body', Ontobee will return the 'body of vertebra' to you. It indicates that Ontobee can search the synonym.

Oliver


________________________________

**Comment by nicolevasilevsky** [comment]
Ontobee does not seem to retrieve synonyms from MP. Some examples:

MP Term: increased desmoid tumor incidence
Synonym: musculo-aponeurotic fibromatosis
Synonym: aggressive fibromatosis

MP term: abnormal cochlear hair cell development
Synonym: abnormal auditory hair cell development

![image](https://cloud.githubusercontent.com/assets/6722114/6193697/b1c17b32-b372-11e4-8d20-6ef5e6867f89.png)

**Comment by cmungall** [comment]
Maybe ontobee doesn't use the oboInOwl vocab?

**Comment by ontoden** [comment]
It's possible. Let me check it out.
Oliver

________________________________

**Comment by cmungall** [comment]
Any progress? This should be trivial?

**Comment by ontoden** [comment]
The reason why Ontobee could not retrieve synonyms from MP and UBERON is because these two ontologies and several others used:
  has_exact_synonym
  http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
for indicating synonyms.

Ontobee by default used IAO:“alternative term” as synonyms.

After we found the issue, I asked Edison to fix it. Thanks, Edison, for working on this.

This should be fixed in Ontobee by Edison for now. Please check out.

It appears that there are three other types of “synonyms”:
  has_related_synonym: http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym
  has_narrow_synonym: http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym
  has_broad_synonym: http://www.geneontology.org/formats/oboInOwl#hasBroadSynonym

They appear not “exact”. We don’t know if we want to include these “synonyms” into our synonym searching function. I think we will need to obtain some consensus on this issue first before we implement it.

Oliver

**Comment by ontoden** [comment]
Hi Chris,
This is the reason.
Edison in my group has now fixed it in Ontobee.
See my previous reply.
Oliver


From: He, Yongqun [mailto:yongqunh@med.umich.edu]
Sent: Friday, February 13, 2015 7:55 PM
To: ontoden/ontobee; ontoden/ontobee
Cc: ontoden
Subject: RE: [ontobee] search for synonyms (#35)

It's possible. Let me check it out.
Oliver
________________________________

**Comment by cmungall** [comment]
Of course you will want to include the other synonym scopes

**Comment by linikujp** [comment]
I suggest that the broader and narrower synonym terms should be included in
the searching query.

In the result section, those types of synonyms should be shown.

Best,
Asiyah

**Comment by e4ong1031** [comment]
The keyword searching function against has_exact_synonym, has_related_synonym, has_narrow_synonym and has_broad_synonym is now implemented in Ontobee.

**Comment by linikujp** [comment]
Great!  Thanks, Edison!
How about the result page?

**Comment by ontoden** [comment]
For example,
The term:
http://purl.obolibrary.org/obo/UBERON_0003834
label: thoracic segment blood vessel

has_exact_synonym: thorax blood vessel; blood vessel of thorax
has_related_synonym: upper body blood vessel

Now you can search these synonyms in Ontobee, for example,
http://www.ontobee.org/browser/index.php?keywords=upper+body+blood+vessel&Submit2=Search+terms&o=UBERON

Oliver

**Comment by linikujp** [comment]
Looks good to me.

Thanks!
Asiyah

**Comment by cmungall** [comment]
@e4ong1031 you rock!

**Comment by cmungall** [comment]
This has been a major issue for ontobee for a while, it's worth calling out this improvement, e.g. in a news page or tweet

**Comment by ontoden** [comment]
Good point. I have added this to the Ontobee news page: http://www.ontobee.org/news.php. Thanks.
