### ISSUE TITLE
Issue with page display

### ISSUE THREAD

**Issue by alanruttenberg** [OntoZoo/ontobee#42]
Go to OBI, search for "conclusion". Click on the result with label "conclusion". Bang!

**Comment by ontoden** [comment]
Edison Ong, my bioinformatics student, has solved this issue. Please check.

Basically, this issue is related to the oboInOwl:Obsolete_Class, which could not be solved previously:
http://www.ontobee.org/browser/rdf.php?o=OBI&iri=http://purl.obolibrary.org/obo/IAO_0000035
http://www.ontobee.org/browser/rdf.php?o=OBI&iri=http://www.geneontology.org/formats/oboInOwl%23ObsoleteClass
you should be able to see these terms for now with no problem.

Oliver

**Comment by ontoden** [comment]
Thanks Edison for fixing the issues.

Jie
