### ISSUE TITLE
Please add ncro.owl

### ISSUE THREAD

**Issue by alanruttenberg** [OntoZoo/ontobee#57]
see http://www.obofoundry.org/ontology/ncro.html
You should be able to load it from http://purl.obolibrary.org/obo/ncro.owl once the pull request https://github.com/OBOFoundry/purl.obolibrary.org/compare/alanruttenberg-ncro-1?expand=1 I put in for the PURLs takes effect.

**Comment by alanruttenberg** [comment]
You can load it from the repository for now

**Comment by e4ong1031** [comment]
NCRO is loaded to ontobee.

Currently, I do URL mapping, http://purl.obolibrary.org/obo/ncro/imports.owl to https://raw.githubusercontent.com/OmniSearch/ncro/master/src/ontology/imports.owl, in the loading script. Hopefully the URL will be resolved later.

Thanks.

**Comment by alanruttenberg** [comment]
Thanks! PURLs should be alive in a few hours. What is the "source" field listed at http://www.ontobee.org/ontology/NCRO ? We don't currently have any assets at berkeleybop.
Also, how often does this get reloaded? I expect there to be a bunch of changes over the next month. Should I just put in an issue when it needs to be reloaded?

**Comment by e4ong1031** [comment]
The source should be the final URL directed by http://purl.obolibrary.org/obo/ncro.owl. 

Because I currently use alternative download link you provided (https://raw.githubusercontent.com/OmniSearch/ncro/master/src/ontology/ncro.owl), the source is not updated and still has its old value. Do you want to remove the source field until the purl URL resolved?

I am planning to start the weekly OBO update early in December.

**Comment by alanruttenberg** [comment]
TBH, I don't think the source should be listed at all. It's pretty irrelevant as the PURLs are the official way to get the ontologies.

**Comment by cmungall** [comment]
You mean this part?

```
#build:
#  source_url: http://purl.obofoundry.org/obo/obi/repository/trunk/src/ontology/branches/
```

This part is useful if you want a generic build pipeline to be executed for you nightly in berkeley and deposited in berkeleybop.org/ontologies/

This is useful for various groups:

 - they don't have technical expertise to make a build themselves, esp. if working in oboedit
 - their downstream product files are too big for github

But it's becoming less and less necessary as various other things improve.

**Comment by cmungall** [comment]
http://obofoundry.org/faq/what-is-the-build-field.html

**Comment by alanruttenberg** [comment]
I wasn't questioning the build pipeline, just the relevance of exposing the information in Ontobee. The concern is that people will record the source rather than use the PURL.

**Comment by cmungall** [comment]
ah didn't realize this was @e4ong1031 from ontobee - in this case yes, no need to make this visible in ontobee or other ontology browsers. The purl should be prominent for all ontologies.

**Comment by alanruttenberg** [comment]
Could you please change the name, as listed on ontobee, to "Non-Coding RNA Ontology"? (capitalize the first two words).

Thanks

**Comment by e4ong1031** [comment]
The ontobee update script follow the value retrieved from OBO ontology list, http://obofoundry.github.io/registry/ontologies.jsonld. And in this json file, the title of ncro is set to be "non-coding RNA Ontology".

I will suggest to change this value in OBO registry. Otherwise the name will change back to "non-coding" every time ontobee update from OBO.
