### ISSUE TITLE
Sequence Ontology properties do not resolve

### ISSUE THREAD

**Issue by arnikz** [OntoZoo/ontobee#91]
Hi,

I get blank pages when requesting SO properties (e.g. http://purl.obolibrary.org/obo/SO_has_part). Could you please look into this? Thank you.

**Comment by e4ong1031** [comment]
Hi arnikz,

The object property does exist in the Ontobee system, http://www.ontobee.org/ontology/SO?iri=http://purl.obolibrary.org/obo/so-xp.obo%23has_part.

When you go to the http://purl.obolibrary.org/obo/SO_has_part, this link redirected to http://www.ontobee.org/ontology/SO_has?iri=http://purl.obolibrary.org/obo/SO_has_part, which pointed to SO_has instead of SO. Seems like there is a misdirection in the PURL obolibrary. For now, please visit the Ontobee main page to browse the SO terms.

Thanks.

**Comment by arnikz** [comment]
Thanks @e4ong1031 for clarifying. I will then post this issue to [purl.obolibrary.org](https://github.com/OBOFoundry/purl.obolibrary.org).

**Comment by cmungall** [comment]
I recommend SO uses the standard RO/BFO properties

If the source version of SO is .obo, there is a quick fix for this. Just add an xref next to each term (for the gory details see owlcollab.github.io/oboformat/doc/obo-syntax.html#4.4)

See any other ontology for details. E.g. in GO:

```
[Typedef]
id: part_of
name: part of
xref: BFO:0000050
is_transitive: true
```

**Comment by jamesaoverton** [comment]
The PURL system is working as designed, matching term IDs that conform to the [OBO ID policy](http://www.obofoundry.org/id-policy.html): ontology ID space + underscore + digits.

It's possible to add a special case for [SO_has_part](http://purl.obolibrary.org/obo/SO_has_part) (here [obo.yml](https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/obo.yml#L22)), but once added it has to be supported forever. It would be better to follow @cmungall's recommendation.
